name: ci
on:
  push:
    branches:
      - main
      - trying
      - staging
    tags: '*'
  pull_request:

jobs:
  test:
    name: ci ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x64
        version: ['1.10', '1.11']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        exclude:
          - os: windows-latest
            version: '1.11'
        include:
          - os: windows-2022
            version: '1.11'
            arch: x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/cache@v1
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@v1
        env:
          JULIA_PLOTS_BACKEND: "unicodeplots"
      - uses: julia-actions/julia-runtest@v1
        env:
          JULIA_PLOTS_BACKEND: "unicodeplots"
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
        with:
          file: lcov.info
          token: ${{secrets.CODECOV_TOKEN}}
