name: ci
on:
  push:
    branches:
      - main
      - trying
      - staging
    tags: '*'
  pull_request:

jobs:
  test:
    name: ci ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/cache@v1
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@v1
        env:
          JULIA_PLOTS_BACKEND: "unicodeplots"
      - uses: julia-actions/julia-runtest@v1
        env:
          JULIA_PLOTS_BACKEND: "unicodeplots"
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
        with:
          file: lcov.info
          token: ${{secrets.CODECOV_TOKEN}}
